import type { SoundProfile } from "@/lib/sound/profiles";

const SPORT_BOX = {
  gearRatios: [14.5, 9.2, 6.8, 5.2, 4.2, 3.5, 3.0],
  idleRpm: 880,
  redlineRpm: 8000,
  shiftSmoothing: 0.11,
};

const MUSCLE_BOX = {
  gearRatios: [12.5, 7.8, 5.2, 3.9, 3.1],
  idleRpm: 680,
  redlineRpm: 6000,
  shiftSmoothing: 0.28,
};

const TURBO6_BOX = {
  gearRatios: [13.8, 8.6, 6.2, 4.8, 3.9, 3.3, 2.9],
  idleRpm: 750,
  redlineRpm: 7000,
  shiftSmoothing: 0.14,
};

const BIKE_BOX = {
  gearRatios: [18, 13, 10.2, 8.4, 7.2, 6.4],
  idleRpm: 1200,
  redlineRpm: 14000,
  shiftSmoothing: 0.05,
};

const TWIN_BOX = {
  gearRatios: [14, 9.5, 7.0, 5.5, 4.5, 3.8],
  idleRpm: 900,
  redlineRpm: 5500,
  shiftSmoothing: 0.22,
};

/** 25 additional built-in Sound Profiles. */
export const EXPANSION_PROFILES: SoundProfile[] = [
  {
    id: "flat-six-sport",
    name: "Flat-Six Sport",
    category: "Classic",
    traits: ["Raspy", "Mechanical", "Precise"],
    description: "A tight, raspy midrange character with precise throttle and less exhaust mass.",
    drivetrainMode: "virtual-transmission",
    motionModel: "virtual-transmission",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 38,
      harmonics: [1, 2, 3.02, 4.5, 6.1],
      waveResponse: 1.05,
      filterBase: 320,
      filterRange: 4200,
      noise: 0.11,
      detune: 5,
      wave: "sawtooth",
      textures: [
        { kind: "sizzle", level: 0.12, tone: 2800, speedScale: 1 },
        { kind: "wind", level: 0.14, tone: 1600, speedScale: 1 },
      ],
    },
    transmission: SPORT_BOX,
  },
  {
    id: "american-muscle-v8",
    name: "American Muscle V8",
    category: "Classic",
    traits: ["Lumpy", "Raw", "Thunderous"],
    description: "Uneven idle, heavy exhaust and slower inertia. A rawer V8 personality than GT V8.",
    drivetrainMode: "virtual-transmission",
    motionModel: "virtual-transmission",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 24,
      harmonics: [1, 2, 2.98, 4],
      waveResponse: 0.75,
      filterBase: 180,
      filterRange: 2200,
      noise: 0.17,
      detune: 14,
      wave: "sawtooth",
      textures: [{ kind: "rumble", level: 0.36, tone: 95, speedScale: 0.6, surge: 0.7 }],
    },
    transmission: MUSCLE_BOX,
  },
  {
    id: "turbo-inline-6",
    name: "Turbo Inline-6",
    category: "Classic",
    traits: ["Smooth", "Boosted", "Elastic"],
    description: "Smooth six-cylinder harmonics with progressive turbo build and midrange torque.",
    drivetrainMode: "virtual-transmission",
    motionModel: "virtual-transmission",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 32,
      harmonics: [1, 2, 3, 4.02, 6],
      waveResponse: 0.95,
      filterBase: 280,
      filterRange: 3600,
      noise: 0.12,
      detune: 4,
      wave: "sawtooth",
      textures: [{ kind: "sizzle", level: 0.1, tone: 3600, speedScale: 1 }],
      signals: [{ kind: "whistle", everySeconds: 10, jitter: 4, level: 0.08, tone: 2800, speedLinked: true }],
    },
    transmission: TURBO6_BOX,
  },
  {
    id: "electric-hypercar",
    name: "Electric Hypercar",
    category: "Future",
    traits: ["Instant", "Intense", "Synthetic"],
    description: "Believable high-performance EV: motor harmonics, inverter texture and regen snap.",
    drivetrainMode: "continuous",
    motionModel: "continuous",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 90,
      harmonics: [1, 2, 3.01, 5],
      waveResponse: 1.25,
      filterBase: 400,
      filterRange: 5000,
      noise: 0.1,
      noiseColor: "pink",
      detune: 6,
      wave: "sawtooth",
      filterQ: 2.4,
      textures: [
        { kind: "sizzle", level: 0.14, tone: 4800, speedScale: 1 },
        { kind: "wind", level: 0.22, tone: 2000, speedScale: 1 },
      ],
    },
  },
  {
    id: "formula-electric",
    name: "Formula Electric",
    category: "Motorsport",
    traits: ["Whining", "Technical", "Fast"],
    description: "Technical motorsport EV: motor whine, inverter cluster and reduction-gear mesh.",
    drivetrainMode: "continuous",
    motionModel: "continuous",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 140,
      harmonics: [1, 2, 3, 5],
      waveResponse: 1.35,
      filterBase: 600,
      filterRange: 6200,
      noise: 0.08,
      detune: 3,
      wave: "sawtooth",
      coreLevel: 0.55,
      textures: [
        { kind: "sizzle", level: 0.16, tone: 5500, speedScale: 1 },
        { kind: "wind", level: 0.28, tone: 2400, speedScale: 1 },
      ],
    },
  },
  {
    id: "neon-drive",
    name: "Neon Drive",
    category: "Future",
    traits: ["Digital", "Pulsing", "Night"],
    description: "A reactive nighttime electronic soundscape of pulses and harmonic tension.",
    drivetrainMode: "continuous",
    motionModel: "event-driven",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 72,
      harmonics: [1, 1.5, 2, 3],
      waveResponse: 1.1,
      filterBase: 280,
      filterRange: 3800,
      noise: 0.06,
      detune: 8,
      wave: "square",
      lfoRate: 2.4,
      lfoDepth: 40,
      lfoTarget: "amp",
      textures: [{ kind: "sizzle", level: 0.1, tone: 4200, speedScale: 0.9, surge: 0.4 }],
    },
  },
  {
    id: "maglev-train",
    name: "Maglev Train",
    category: "Machines",
    traits: ["Linear", "Floating", "High-Speed"],
    description: "Frictionless linear propulsion, guideway hum and aerodynamic pressure.",
    drivetrainMode: "continuous",
    motionModel: "physical-machine",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 55,
      harmonics: [1, 1.5, 2.02],
      waveResponse: 0.7,
      filterBase: 200,
      filterRange: 2800,
      noise: 0.15,
      noiseColor: "pink",
      detune: 5,
      wave: "sine",
      coreLevel: 0.4,
      textures: [
        { kind: "wind", level: 0.22, tone: 1800, speedScale: 1, surge: 0.15 },
        { kind: "rumble", level: 0.22, tone: 60, speedScale: 0.5 },
      ],
    },
  },
  {
    id: "high-speed-train",
    name: "High-Speed Train",
    category: "Machines",
    traits: ["Aero", "Metallic", "Progressive"],
    description: "Electric traction, rail resonance and aero rush with sparse track joints.",
    drivetrainMode: "continuous",
    motionModel: "physical-machine",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 48,
      harmonics: [1, 2.01, 3],
      waveResponse: 0.85,
      filterBase: 220,
      filterRange: 3200,
      noise: 0.14,
      noiseColor: "pink",
      detune: 6,
      wave: "triangle",
      coreLevel: 0.45,
      rhythm: { kind: "clack", baseRate: 0.3, rateScale: 1.2, level: 0.08, tone: 900 },
      textures: [
        { kind: "wind", level: 0.24, tone: 2000, speedScale: 1 },
        { kind: "rumble", level: 0.2, tone: 80, speedScale: 0.7 },
      ],
    },
  },
  {
    id: "submarine",
    name: "Submarine",
    category: "Future",
    traits: ["Deep", "Sonar", "Pressurized"],
    description: "Enclosed hull resonance, electric propulsion and rare sonar pulses.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 36,
      harmonics: [1, 1.5, 2],
      waveResponse: 0.55,
      filterBase: 90,
      filterRange: 900,
      noise: 0.15,
      noiseColor: "pink",
      detune: 10,
      wave: "sine",
      coreLevel: 0.5,
      textures: [
        { kind: "water", level: 0.28, tone: 400, speedScale: 0.8, surge: 0.2 },
        { kind: "rumble", level: 0.34, tone: 50, speedScale: 0.4 },
      ],
      signals: [{ kind: "sonar", everySeconds: 28, jitter: 12, level: 0.1, tone: 720 }],
    },
  },
  {
    id: "jet-ski",
    name: "Jet Ski",
    category: "Nautical",
    traits: ["Water", "Sharp", "Playful"],
    description: "Compact high-rev watercraft with impeller rush, spray and hull slap.",
    drivetrainMode: "continuous",
    motionModel: "continuous",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 70,
      harmonics: [1, 2.02, 3.5],
      waveResponse: 1.2,
      filterBase: 360,
      filterRange: 4200,
      noise: 0.22,
      noiseColor: "pink",
      detune: 10,
      wave: "sawtooth",
      coreLevel: 0.5,
      rhythm: { kind: "splash", baseRate: 2, rateScale: 8, level: 0.28, tone: 900 },
      textures: [
        { kind: "water", level: 0.32, tone: 1800, speedScale: 1, surge: 0.8 },
        { kind: "wind", level: 0.2, tone: 2600, speedScale: 1 },
      ],
    },
  },
  {
    id: "motorcycle-superbike",
    name: "Motorcycle Superbike",
    category: "Motorsport",
    traits: ["Raw", "Screaming", "Immediate"],
    description: "Exposed high-rev four-cylinder character with instant throttle and fast shifts.",
    drivetrainMode: "virtual-transmission",
    motionModel: "virtual-transmission",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 48,
      harmonics: [1, 2, 3.02, 5, 7, 9],
      waveResponse: 1.4,
      filterBase: 520,
      filterRange: 5800,
      noise: 0.12,
      detune: 3,
      wave: "sawtooth",
      textures: [
        { kind: "sizzle", level: 0.16, tone: 4800, speedScale: 1 },
        { kind: "wind", level: 0.3, tone: 2200, speedScale: 1 },
      ],
    },
    transmission: BIKE_BOX,
  },
  {
    id: "big-twin",
    name: "Big Twin",
    category: "Classic",
    traits: ["Loping", "Heavy", "Rhythmic"],
    description: "Large V-twin cadence with heavy flywheel feel and pronounced idle pulse separation.",
    drivetrainMode: "virtual-transmission",
    motionModel: "virtual-transmission",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 28,
      harmonics: [1, 1.98, 3.1],
      waveResponse: 0.85,
      filterBase: 200,
      filterRange: 2400,
      noise: 0.12,
      detune: 12,
      wave: "sawtooth",
      rhythm: { kind: "putt", baseRate: 3.2, rateScale: 10, level: 0.34, tone: 100 },
      textures: [{ kind: "rumble", level: 0.24, tone: 85, speedScale: 0.55 }],
    },
    transmission: TWIN_BOX,
  },
  {
    id: "snowmobile",
    name: "Snowmobile",
    category: "Machines",
    traits: ["Two-Stroke", "Crisp", "Snowy"],
    description: "Crisp two-stroke character with CVT belt whine and soft snow spray.",
    drivetrainMode: "continuous",
    motionModel: "continuous",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 64,
      harmonics: [1, 2.03, 3.1, 4.5],
      waveResponse: 1.15,
      filterBase: 400,
      filterRange: 4600,
      noise: 0.15,
      noiseColor: "pink",
      detune: 8,
      wave: "sawtooth",
      textures: [
        { kind: "wind", level: 0.24, tone: 1400, speedScale: 1 },
        { kind: "gravel", level: 0.16, tone: 1800, speedScale: 1, surge: 2 },
      ],
    },
  },
  {
    id: "tank",
    name: "Tank",
    category: "Machines",
    traits: ["Tracked", "Heavy", "Mechanical"],
    description: "Low diesel load, track cadence and hull resonance. Mass without combat audio.",
    drivetrainMode: "continuous",
    motionModel: "physical-machine",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 22,
      harmonics: [1, 2, 3],
      waveResponse: 0.55,
      filterBase: 120,
      filterRange: 1100,
      noise: 0.17,
      noiseColor: "pink",
      detune: 16,
      wave: "square",
      coreLevel: 0.45,
      rhythm: { kind: "clack", baseRate: 2.5, rateScale: 10, level: 0.36, tone: 280 },
      textures: [{ kind: "rumble", level: 0.4, tone: 70, speedScale: 0.7, surge: 0.5 }],
    },
  },
  {
    id: "construction-monster",
    name: "Construction Monster",
    category: "Machines",
    traits: ["Hydraulic", "Diesel", "Industrial"],
    description: "Industrial diesel under load with hydraulic pump whine and mechanical strain.",
    drivetrainMode: "continuous",
    motionModel: "physical-machine",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 26,
      harmonics: [1, 2.02, 3],
      waveResponse: 0.6,
      filterBase: 140,
      filterRange: 1600,
      noise: 0.14,
      detune: 14,
      wave: "square",
      lfoRate: 1.8,
      lfoDepth: 120,
      lfoTarget: "filter",
      textures: [
        { kind: "rumble", level: 0.32, tone: 75, speedScale: 0.5 },
        { kind: "sizzle", level: 0.12, tone: 3200, speedScale: 0.7, surge: 1.5 },
      ],
    },
  },
  {
    id: "horse-gallop",
    name: "Horse Gallop",
    category: "Heritage",
    traits: ["Fast", "Rhythmic", "Cinematic"],
    description: "Pure horse gait states from walk to gallop, without a carriage.",
    drivetrainMode: "continuous",
    motionModel: "cadence",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 50,
      harmonics: [1, 2],
      waveResponse: 0.8,
      filterBase: 200,
      filterRange: 900,
      noise: 0.05,
      detune: 10,
      wave: "triangle",
      coreLevel: 0.15,
      rhythm: { kind: "gallop", baseRate: 1.0, rateScale: 3.2, level: 0.38, tone: 360 },
      textures: [
        { kind: "gravel", level: 0.18, tone: 1600, speedScale: 1, surge: 1.5 },
        { kind: "wind", level: 0.1, tone: 800, speedScale: 0.6 },
      ],
    },
  },
  {
    id: "dragon",
    name: "Dragon",
    category: "Future",
    traits: ["Breathing", "Roaring", "Mythic"],
    description: "Organic breath, wing air and rare roar events. Original fantasy, not a film cue.",
    drivetrainMode: "continuous",
    motionModel: "event-driven",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 40,
      harmonics: [1, 1.5, 2.02],
      waveResponse: 0.75,
      filterBase: 120,
      filterRange: 1800,
      noise: 0.17,
      noiseColor: "pink",
      detune: 18,
      wave: "sawtooth",
      coreLevel: 0.35,
      lfoRate: 0.22,
      lfoDepth: 80,
      lfoTarget: "amp",
      textures: [
        { kind: "rumble", level: 0.36, tone: 55, speedScale: 0.4, surge: 0.25 },
        { kind: "wind", level: 0.28, tone: 900, speedScale: 0.85, surge: 0.5 },
      ],
      signals: [{ kind: "roar", everySeconds: 14, jitter: 7, level: 0.2, tone: 72 }],
    },
  },
  {
    id: "thunder-beast",
    name: "Thunder Beast",
    category: "Future",
    traits: ["Dark", "Organic", "Powerful"],
    description: "Part creature, part pressure wave, part weather. Premium cinematic mass.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 34,
      harmonics: [1, 1.98, 2.5],
      waveResponse: 0.7,
      filterBase: 100,
      filterRange: 1600,
      noise: 0.15,
      noiseColor: "pink",
      detune: 20,
      wave: "triangle",
      coreLevel: 0.4,
      textures: [
        { kind: "rumble", level: 0.42, tone: 48, speedScale: 0.35, surge: 0.12 },
        { kind: "wind", level: 0.3, tone: 700, speedScale: 0.9, surge: 0.6 },
      ],
      signals: [{ kind: "beam", everySeconds: 24, jitter: 12, level: 0.1, tone: 70 }],
    },
  },
  {
    id: "retro-arcade",
    name: "Retro Arcade",
    category: "Musical",
    traits: ["8-bit", "Reactive", "Nostalgic"],
    description: "Original console-inspired square and noise responses. No borrowed melodies.",
    drivetrainMode: "continuous",
    motionModel: "event-driven",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 110,
      harmonics: [1, 2],
      waveResponse: 1.2,
      filterBase: 600,
      filterRange: 4000,
      noise: 0.08,
      detune: 0,
      wave: "square",
      lfoRate: 8,
      lfoDepth: 20,
      lfoTarget: "pitch",
    },
  },
  {
    id: "synthwave-drive",
    name: "Synthwave Drive",
    category: "Musical",
    traits: ["Retro", "Neon", "Musical"],
    description: "Motion-reactive ambient groove: warm pad, soft bass pulse, light arpeggio.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 65,
      harmonics: [1, 1.5, 2, 3],
      waveResponse: 0.85,
      filterBase: 240,
      filterRange: 3200,
      noise: 0.08,
      detune: 6,
      wave: "sawtooth",
      lfoRate: 0.15,
      lfoDepth: 200,
      lfoTarget: "filter",
      textures: [{ kind: "sizzle", level: 0.08, tone: 5000, speedScale: 0.7, surge: 0.2 }],
    },
  },
  {
    id: "deep-bass-pulse",
    name: "Deep Bass Pulse",
    category: "Musical",
    traits: ["Minimal", "Physical", "Subtle"],
    description: "Quiet motion feedback focused around 50–160 Hz. The least intrusive profile.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 55,
      harmonics: [1, 2],
      waveResponse: 0.5,
      filterBase: 80,
      filterRange: 400,
      noise: 0.04,
      detune: 2,
      wave: "sine",
      coreLevel: 0.55,
      textures: [{ kind: "rumble", level: 0.18, tone: 70, speedScale: 0.4 }],
    },
  },
  {
    id: "zen-drive",
    name: "Zen Drive",
    category: "Nature",
    traits: ["Calm", "Ambient", "Organic"],
    description: "Soft wind, breath-like resonance and rare chimes. Calming even at speed.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 48,
      harmonics: [1, 1.5],
      waveResponse: 0.4,
      filterBase: 180,
      filterRange: 1400,
      noise: 0.15,
      noiseColor: "pink",
      detune: 12,
      wave: "sine",
      coreLevel: 0.3,
      textures: [
        { kind: "wind", level: 0.4, tone: 900, speedScale: 0.85, surge: 0.18 },
        { kind: "rumble", level: 0.12, tone: 55, speedScale: 0.3 },
      ],
      signals: [{ kind: "whistle", everySeconds: 28, jitter: 14, level: 0.06, tone: 1200 }],
    },
  },
  {
    id: "rain-drive",
    name: "Rain Drive",
    category: "Nature",
    traits: ["Wet", "Soft", "Atmospheric"],
    description: "Movement through rain: drops, wet-road spray and tire wash, not flat hiss.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 40,
      harmonics: [1],
      waveResponse: 0.5,
      filterBase: 400,
      filterRange: 2000,
      noise: 0.26,
      noiseColor: "pink",
      detune: 8,
      wave: "sine",
      coreLevel: 0.12,
      textures: [
        { kind: "water", level: 0.3, tone: 2200, speedScale: 1, surge: 1.2 },
        { kind: "wind", level: 0.14, tone: 1600, speedScale: 0.9 },
      ],
    },
  },
  {
    id: "ocean-drive",
    name: "Ocean Drive",
    category: "Nature",
    traits: ["Waves", "Calm", "Expansive"],
    description: "Ocean motion as driving ambience: swell, foam and wind. Not a boat.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 36,
      harmonics: [1, 1.5],
      waveResponse: 0.45,
      filterBase: 120,
      filterRange: 1200,
      noise: 0.19,
      noiseColor: "pink",
      detune: 14,
      wave: "sine",
      coreLevel: 0.25,
      textures: [
        { kind: "water", level: 0.34, tone: 500, speedScale: 0.7, surge: 0.12 },
        { kind: "wind", level: 0.16, tone: 1100, speedScale: 0.8, surge: 0.2 },
        { kind: "rumble", level: 0.2, tone: 45, speedScale: 0.35 },
      ],
    },
  },
  {
    id: "heartbeat",
    name: "Heartbeat",
    category: "Musical",
    traits: ["Organic", "Rhythmic", "Intimate"],
    description: "A two-part heartbeat that rises with driving intensity, not vehicle speed alone.",
    drivetrainMode: "continuous",
    motionModel: "cadence",
    sourceMode: "procedural",
    voice: {
      baseFrequency: 60,
      harmonics: [1, 2],
      waveResponse: 0.9,
      filterBase: 100,
      filterRange: 600,
      noise: 0.04,
      detune: 2,
      wave: "sine",
      coreLevel: 0.2,
      rhythm: { kind: "putt", baseRate: 1.1, rateScale: 1.4, level: 0.35, tone: 70 },
    },
  },
];
