import type { SoundProfile } from "@/lib/sound/profiles";

/** Minimal SoundProfiles that select the SymphonySynth backend. */
export const SYMPHONY_SOUND_PROFILES: SoundProfile[] = [
  {
    id: "symphony-cinematic-rock",
    name: "Cinematic Rock",
    category: "Musical",
    traits: ["Symphony", "Rock", "Cinematic"],
    description: "Drive Symphony - arrangement shaped by motion intent.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "hybrid",
    access: "free",
    voice: {
      baseFrequency: 110,
      harmonics: [1],
      waveResponse: 0.6,
      filterBase: 400,
      filterRange: 800,
      noise: 0,
      wave: "sine",
      detune: 0,
      coreLevel: 0.5,
    },
  },
  {
    id: "symphony-motion-orchestra",
    name: "Motion Orchestra",
    category: "Musical",
    traits: ["Symphony", "Orchestra", "Strings"],
    description: "Drive Symphony - orchestral layers follow musical intent.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "hybrid",
    access: "free",
    voice: {
      baseFrequency: 130,
      harmonics: [1],
      waveResponse: 0.55,
      filterBase: 500,
      filterRange: 900,
      noise: 0,
      wave: "sine",
      detune: 0,
      coreLevel: 0.5,
    },
  },
  {
    id: "symphony-neon-run",
    name: "Neon Run",
    category: "Musical",
    traits: ["Symphony", "Electronic", "Neon"],
    description: "Drive Symphony - electronic pulse shaped by motion intent.",
    drivetrainMode: "continuous",
    motionModel: "ambient",
    sourceMode: "hybrid",
    access: "free",
    voice: {
      baseFrequency: 110,
      harmonics: [1],
      waveResponse: 0.65,
      filterBase: 450,
      filterRange: 1200,
      noise: 0,
      wave: "sine",
      detune: 0,
      coreLevel: 0.5,
    },
  },
];
