/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalibrateRouteImport } from './routes/calibrate'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as LegalRouteRouteImport } from './routes/legal/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SoundsRouteImport } from './routes/sounds'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LegalAccessibilityRouteImport } from './routes/legal/accessibility'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalImpressumRouteImport } from './routes/legal/impressum'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrateRoute = CalibrateRouteImport.update({
  id: '/calibrate',
  path: '/calibrate',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundsRoute = SoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/debug': typeof DebugRoute
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/garage': typeof GarageRoute
  '/onboarding': typeof OnboardingRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sounds': typeof SoundsRoute
  '/studio': typeof StudioRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/debug': typeof DebugRoute
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/garage': typeof GarageRoute
  '/onboarding': typeof OnboardingRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sounds': typeof SoundsRoute
  '/studio': typeof StudioRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/debug': typeof DebugRoute
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/garage': typeof GarageRoute
  '/onboarding': typeof OnboardingRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sounds': typeof SoundsRoute
  '/studio': typeof StudioRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/about'
    | '/calibrate'
    | '/debug'
    | '/demo'
    | '/drive'
    | '/garage'
    | '/onboarding'
    | '/replay'
    | '/settings'
    | '/share'
    | '/sounds'
    | '/studio'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calibrate'
    | '/debug'
    | '/demo'
    | '/drive'
    | '/garage'
    | '/onboarding'
    | '/replay'
    | '/settings'
    | '/share'
    | '/sounds'
    | '/studio'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/about'
    | '/calibrate'
    | '/debug'
    | '/demo'
    | '/drive'
    | '/garage'
    | '/onboarding'
    | '/replay'
    | '/settings'
    | '/share'
    | '/sounds'
    | '/studio'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CalibrateRoute: typeof CalibrateRoute
  DebugRoute: typeof DebugRoute
  DemoRoute: typeof DemoRoute
  DriveRoute: typeof DriveRoute
  GarageRoute: typeof GarageRoute
  OnboardingRoute: typeof OnboardingRoute
  ReplayRoute: typeof ReplayRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SoundsRoute: typeof SoundsRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibrate': {
      id: '/calibrate'
      path: '/calibrate'
      fullPath: '/calibrate'
      preLoaderRoute: typeof CalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sounds': {
      id: '/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
  }
}

interface LegalRouteRouteChildren {
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CalibrateRoute: CalibrateRoute,
  DebugRoute: DebugRoute,
  DemoRoute: DemoRoute,
  DriveRoute: DriveRoute,
  GarageRoute: GarageRoute,
  OnboardingRoute: OnboardingRoute,
  ReplayRoute: ReplayRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SoundsRoute: SoundsRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
