/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalibrateRouteImport } from './routes/calibrate'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as LegalRouteRouteImport } from './routes/legal/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SoundsRouteImport } from './routes/sounds'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ConnectSessionIdRouteImport } from './routes/connect.$sessionId'
import { Route as DebugBillingRouteImport } from './routes/debug.billing'
import { Route as DebugCalibrationRouteImport } from './routes/debug.calibration'
import { Route as DebugDiagnosticsRouteImport } from './routes/debug.diagnostics'
import { Route as DebugPowertrainRouteImport } from './routes/debug.powertrain'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LegalAccessibilityRouteImport } from './routes/legal/accessibility'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalImpressumRouteImport } from './routes/legal/impressum'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as UpgradeTokenRouteImport } from './routes/upgrade.$token'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiSoundAssetsDeliveryRouteImport } from './routes/api/sound-assets/delivery'
import { Route as ApiSoundAssetsManifestRouteImport } from './routes/api/sound-assets/manifest'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as AuthAccountCallbackRouteImport } from './routes/auth/account/callback'
import { Route as AuthTeslaCallbackRouteImport } from './routes/auth/tesla/callback'
import { Route as AuthAccountGoogleCallbackRouteImport } from './routes/auth/account/google/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrateRoute = CalibrateRouteImport.update({
  id: '/calibrate',
  path: '/calibrate',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRouteRoute = LegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundsRoute = SoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSessionIdRoute = ConnectSessionIdRouteImport.update({
  id: '/connect/$sessionId',
  path: '/connect/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugBillingRoute = DebugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DebugRoute,
} as any)
const DebugCalibrationRoute = DebugCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => DebugRoute,
} as any)
const DebugDiagnosticsRoute = DebugDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => DebugRoute,
} as any)
const DebugPowertrainRoute = DebugPowertrainRouteImport.update({
  id: '/powertrain',
  path: '/powertrain',
  getParentRoute: () => DebugRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRouteRoute,
} as any)
const UpgradeTokenRoute = UpgradeTokenRouteImport.update({
  id: '/upgrade/$token',
  path: '/upgrade/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundAssetsDeliveryRoute = ApiSoundAssetsDeliveryRouteImport.update({
  id: '/api/sound-assets/delivery',
  path: '/api/sound-assets/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundAssetsManifestRoute = ApiSoundAssetsManifestRouteImport.update({
  id: '/api/sound-assets/manifest',
  path: '/api/sound-assets/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountCallbackRoute = AuthAccountCallbackRouteImport.update({
  id: '/auth/account/callback',
  path: '/auth/account/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTeslaCallbackRoute = AuthTeslaCallbackRouteImport.update({
  id: '/auth/tesla/callback',
  path: '/auth/tesla/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountGoogleCallbackRoute =
  AuthAccountGoogleCallbackRouteImport.update({
    id: '/auth/account/google/callback',
    path: '/auth/account/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/debug': typeof DebugRouteWithChildren
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/garage': typeof GarageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sounds': typeof SoundsRoute
  '/studio': typeof StudioRoute
  '/connect/$sessionId': typeof ConnectSessionIdRoute
  '/debug/billing': typeof DebugBillingRoute
  '/debug/calibration': typeof DebugCalibrationRoute
  '/debug/diagnostics': typeof DebugDiagnosticsRoute
  '/debug/powertrain': typeof DebugPowertrainRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/upgrade/$token': typeof UpgradeTokenRoute
  '/legal/': typeof LegalIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/sound-assets/delivery': typeof ApiSoundAssetsDeliveryRoute
  '/api/sound-assets/manifest': typeof ApiSoundAssetsManifestRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/auth/account/callback': typeof AuthAccountCallbackRoute
  '/auth/tesla/callback': typeof AuthTeslaCallbackRoute
  '/auth/account/google/callback': typeof AuthAccountGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/debug': typeof DebugRouteWithChildren
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/garage': typeof GarageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sounds': typeof SoundsRoute
  '/studio': typeof StudioRoute
  '/connect/$sessionId': typeof ConnectSessionIdRoute
  '/debug/billing': typeof DebugBillingRoute
  '/debug/calibration': typeof DebugCalibrationRoute
  '/debug/diagnostics': typeof DebugDiagnosticsRoute
  '/debug/powertrain': typeof DebugPowertrainRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/upgrade/$token': typeof UpgradeTokenRoute
  '/legal': typeof LegalIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/sound-assets/delivery': typeof ApiSoundAssetsDeliveryRoute
  '/api/sound-assets/manifest': typeof ApiSoundAssetsManifestRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/auth/account/callback': typeof AuthAccountCallbackRoute
  '/auth/tesla/callback': typeof AuthTeslaCallbackRoute
  '/auth/account/google/callback': typeof AuthAccountGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/debug': typeof DebugRouteWithChildren
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/garage': typeof GarageRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/replay': typeof ReplayRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sounds': typeof SoundsRoute
  '/studio': typeof StudioRoute
  '/connect/$sessionId': typeof ConnectSessionIdRoute
  '/debug/billing': typeof DebugBillingRoute
  '/debug/calibration': typeof DebugCalibrationRoute
  '/debug/diagnostics': typeof DebugDiagnosticsRoute
  '/debug/powertrain': typeof DebugPowertrainRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/upgrade/$token': typeof UpgradeTokenRoute
  '/legal/': typeof LegalIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/sound-assets/delivery': typeof ApiSoundAssetsDeliveryRoute
  '/api/sound-assets/manifest': typeof ApiSoundAssetsManifestRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/auth/account/callback': typeof AuthAccountCallbackRoute
  '/auth/tesla/callback': typeof AuthTeslaCallbackRoute
  '/auth/account/google/callback': typeof AuthAccountGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal'
    | '/about'
    | '/calibrate'
    | '/debug'
    | '/demo'
    | '/drive'
    | '/garage'
    | '/onboarding'
    | '/pricing'
    | '/replay'
    | '/settings'
    | '/share'
    | '/sounds'
    | '/studio'
    | '/connect/$sessionId'
    | '/debug/billing'
    | '/debug/calibration'
    | '/debug/diagnostics'
    | '/debug/powertrain'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/upgrade/$token'
    | '/legal/'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/sound-assets/delivery'
    | '/api/sound-assets/manifest'
    | '/api/stripe/webhook'
    | '/auth/account/callback'
    | '/auth/tesla/callback'
    | '/auth/account/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calibrate'
    | '/debug'
    | '/demo'
    | '/drive'
    | '/garage'
    | '/onboarding'
    | '/pricing'
    | '/replay'
    | '/settings'
    | '/share'
    | '/sounds'
    | '/studio'
    | '/connect/$sessionId'
    | '/debug/billing'
    | '/debug/calibration'
    | '/debug/diagnostics'
    | '/debug/powertrain'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/upgrade/$token'
    | '/legal'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/sound-assets/delivery'
    | '/api/sound-assets/manifest'
    | '/api/stripe/webhook'
    | '/auth/account/callback'
    | '/auth/tesla/callback'
    | '/auth/account/google/callback'
  id:
    | '__root__'
    | '/'
    | '/legal'
    | '/about'
    | '/calibrate'
    | '/debug'
    | '/demo'
    | '/drive'
    | '/garage'
    | '/onboarding'
    | '/pricing'
    | '/replay'
    | '/settings'
    | '/share'
    | '/sounds'
    | '/studio'
    | '/connect/$sessionId'
    | '/debug/billing'
    | '/debug/calibration'
    | '/debug/diagnostics'
    | '/debug/powertrain'
    | '/legal/accessibility'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/upgrade/$token'
    | '/legal/'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/sound-assets/delivery'
    | '/api/sound-assets/manifest'
    | '/api/stripe/webhook'
    | '/auth/account/callback'
    | '/auth/tesla/callback'
    | '/auth/account/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRouteRoute: typeof LegalRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CalibrateRoute: typeof CalibrateRoute
  DebugRoute: typeof DebugRouteWithChildren
  DemoRoute: typeof DemoRoute
  DriveRoute: typeof DriveRoute
  GarageRoute: typeof GarageRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ReplayRoute: typeof ReplayRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SoundsRoute: typeof SoundsRoute
  StudioRoute: typeof StudioRoute
  ConnectSessionIdRoute: typeof ConnectSessionIdRoute
  UpgradeTokenRoute: typeof UpgradeTokenRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiSoundAssetsDeliveryRoute: typeof ApiSoundAssetsDeliveryRoute
  ApiSoundAssetsManifestRoute: typeof ApiSoundAssetsManifestRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  AuthAccountCallbackRoute: typeof AuthAccountCallbackRoute
  AuthTeslaCallbackRoute: typeof AuthTeslaCallbackRoute
  AuthAccountGoogleCallbackRoute: typeof AuthAccountGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibrate': {
      id: '/calibrate'
      path: '/calibrate'
      fullPath: '/calibrate'
      preLoaderRoute: typeof CalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sounds': {
      id: '/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/$sessionId': {
      id: '/connect/$sessionId'
      path: '/connect/$sessionId'
      fullPath: '/connect/$sessionId'
      preLoaderRoute: typeof ConnectSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/billing': {
      id: '/debug/billing'
      path: '/billing'
      fullPath: '/debug/billing'
      preLoaderRoute: typeof DebugBillingRouteImport
      parentRoute: typeof DebugRoute
    }
    '/debug/calibration': {
      id: '/debug/calibration'
      path: '/calibration'
      fullPath: '/debug/calibration'
      preLoaderRoute: typeof DebugCalibrationRouteImport
      parentRoute: typeof DebugRoute
    }
    '/debug/diagnostics': {
      id: '/debug/diagnostics'
      path: '/diagnostics'
      fullPath: '/debug/diagnostics'
      preLoaderRoute: typeof DebugDiagnosticsRouteImport
      parentRoute: typeof DebugRoute
    }
    '/debug/powertrain': {
      id: '/debug/powertrain'
      path: '/powertrain'
      fullPath: '/debug/powertrain'
      preLoaderRoute: typeof DebugPowertrainRouteImport
      parentRoute: typeof DebugRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRouteRoute
    }
    '/upgrade/$token': {
      id: '/upgrade/$token'
      path: '/upgrade/$token'
      fullPath: '/upgrade/$token'
      preLoaderRoute: typeof UpgradeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sound-assets/delivery': {
      id: '/api/sound-assets/delivery'
      path: '/api/sound-assets/delivery'
      fullPath: '/api/sound-assets/delivery'
      preLoaderRoute: typeof ApiSoundAssetsDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sound-assets/manifest': {
      id: '/api/sound-assets/manifest'
      path: '/api/sound-assets/manifest'
      fullPath: '/api/sound-assets/manifest'
      preLoaderRoute: typeof ApiSoundAssetsManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account/callback': {
      id: '/auth/account/callback'
      path: '/auth/account/callback'
      fullPath: '/auth/account/callback'
      preLoaderRoute: typeof AuthAccountCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/tesla/callback': {
      id: '/auth/tesla/callback'
      path: '/auth/tesla/callback'
      fullPath: '/auth/tesla/callback'
      preLoaderRoute: typeof AuthTeslaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account/google/callback': {
      id: '/auth/account/google/callback'
      path: '/auth/account/google/callback'
      fullPath: '/auth/account/google/callback'
      preLoaderRoute: typeof AuthAccountGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteRouteChildren {
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteRouteChildren: LegalRouteRouteChildren = {
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteRouteWithChildren = LegalRouteRoute._addFileChildren(
  LegalRouteRouteChildren,
)

interface DebugRouteChildren {
  DebugBillingRoute: typeof DebugBillingRoute
  DebugCalibrationRoute: typeof DebugCalibrationRoute
  DebugDiagnosticsRoute: typeof DebugDiagnosticsRoute
  DebugPowertrainRoute: typeof DebugPowertrainRoute
}

const DebugRouteChildren: DebugRouteChildren = {
  DebugBillingRoute: DebugBillingRoute,
  DebugCalibrationRoute: DebugCalibrationRoute,
  DebugDiagnosticsRoute: DebugDiagnosticsRoute,
  DebugPowertrainRoute: DebugPowertrainRoute,
}

const DebugRouteWithChildren = DebugRoute._addFileChildren(DebugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRouteRoute: LegalRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CalibrateRoute: CalibrateRoute,
  DebugRoute: DebugRouteWithChildren,
  DemoRoute: DemoRoute,
  DriveRoute: DriveRoute,
  GarageRoute: GarageRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ReplayRoute: ReplayRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SoundsRoute: SoundsRoute,
  StudioRoute: StudioRoute,
  ConnectSessionIdRoute: ConnectSessionIdRoute,
  UpgradeTokenRoute: UpgradeTokenRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiSoundAssetsDeliveryRoute: ApiSoundAssetsDeliveryRoute,
  ApiSoundAssetsManifestRoute: ApiSoundAssetsManifestRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  AuthAccountCallbackRoute: AuthAccountCallbackRoute,
  AuthTeslaCallbackRoute: AuthTeslaCallbackRoute,
  AuthAccountGoogleCallbackRoute: AuthAccountGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
