/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalibrateRouteImport } from './routes/calibrate'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DriveRouteImport } from './routes/drive'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SoundsRouteImport } from './routes/sounds'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrateRoute = CalibrateRouteImport.update({
  id: '/calibrate',
  path: '/calibrate',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DriveRoute = DriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundsRoute = SoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/sounds': typeof SoundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/sounds': typeof SoundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calibrate': typeof CalibrateRoute
  '/demo': typeof DemoRoute
  '/drive': typeof DriveRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/sounds': typeof SoundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calibrate'
    | '/demo'
    | '/drive'
    | '/onboarding'
    | '/settings'
    | '/sounds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calibrate'
    | '/demo'
    | '/drive'
    | '/onboarding'
    | '/settings'
    | '/sounds'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calibrate'
    | '/demo'
    | '/drive'
    | '/onboarding'
    | '/settings'
    | '/sounds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalibrateRoute: typeof CalibrateRoute
  DemoRoute: typeof DemoRoute
  DriveRoute: typeof DriveRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SoundsRoute: typeof SoundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibrate': {
      id: '/calibrate'
      path: '/calibrate'
      fullPath: '/calibrate'
      preLoaderRoute: typeof CalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drive': {
      id: '/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof DriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sounds': {
      id: '/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof SoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalibrateRoute: CalibrateRoute,
  DemoRoute: DemoRoute,
  DriveRoute: DriveRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SoundsRoute: SoundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
